apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: db01
spec:
  selector:
    app: db01
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

