apiVersion: v1
kind: Service
metadata:
  name: mc-service
  labels:
    app: mc01
spec:
  selector:
    app: mc01
  ports:
    - protocol: TCP
      port: 11211
      targetPort: 11211
  type: ClusterIP

