apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app01
  ports:
    - protocol: TCP
      port: 80        # External port
      targetPort: 8080 # App container port
      nodePort: 30080  # Fixed port on the node
  type: NodePort

