apiVersion: v1
kind: Service
metadata:
  name: rmq-service
  labels:
    app: rmq01
spec:
  selector:
    app: rmq01
  ports:
    - protocol: TCP
      port: 15672
      targetPort: 15672
  type: ClusterIP
